// Generated by CoffeeScript 1.10.0
var webpackConfig;

webpackConfig = require('./webpack.config.js');

module.exports = function(grunt) {
  require('load-grunt-tasks')(grunt);
  grunt.initConfig({
    clean: {
      dev: ['.tmp'],
      release: ['dist']
    },
    webpack: {
      app: webpackConfig.generateAppConfig(false),
      serverD: webpackConfig.generateServerConfig(false)
    },
    'webpack-dev-server': {
      app: {
        webpack: webpackConfig.generateAppConfig(true),
        publicPath: '/',
        hot: true,
        historyApiFallback: true,
        stats: {
          colors: true
        },
        port: 3001
      }
    },
    watch: {
      server: {
        files: './dist/public/**/*',
        tasks: ['webpack-dev-server']
      }
    },
    copy: {
      main: {
        files: [
          {
            expand: true,
            cwd: 'src/server/views/',
            src: ['**'],
            dest: 'dist/views/'
          }
        ]
      }
    }
  });
  grunt.registerTask('default', ['clean:dev', 'webpack-dev-server', 'watch']);
  return grunt.registerTask('release', ['clean:release', 'copy', 'webpack']);
};
